dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake

before_script:
- cmake --version
- mkdir build
- cd build
- cmake . ${TRAVIS_BUILD_DIR}

script:
- make