matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.8"

  before_install:
    - eval "${MATRIX_EVAL}"